Repository BookitList/BookitList_backend, pull requests merged in 2024-03, with the labels that each got.

#187 [Feat] @Transactional 기본값 통일
  src/main/java/cotato/bookitlist/auth/service/AuthService.java
  src/main/java/cotato/bookitlist/config/RedisConfig.java
  src/main/java/cotato/bookitlist/member/service/MemberService.java
  src/main/java/cotato/bookitlist/post/service/PostService.java
  src/main/java/cotato/bookitlist/review/service/ReviewService.java
Labels: ♻️ Refactor

#189 [Feat] README 작성
  README.md
Labels: 📝 Docs

#191 [Feat] 패키지 순환 참조 해결
  src/main/java/cotato/bookitlist/auth/service/AuthService.java
  src/main/java/cotato/bookitlist/book/controller/BookLikeController.java
  src/main/java/cotato/bookitlist/member/controller/MemberController.java
  src/main/java/cotato/bookitlist/member/domain/Member.java
  src/main/java/cotato/bookitlist/member/repository/MemberRepository.java
  src/main/java/cotato/bookitlist/post/controller/PostController.java
  src/main/java/cotato/bookitlist/post/controller/PostLikeController.java
  src/main/java/cotato/bookitlist/review/controller/ReviewController.java
  src/main/java/cotato/bookitlist/review/controller/ReviewLikeController.java
  src/main/java/cotato/bookitlist/security/CustomAccessDeniedHandler.java
  src/main/java/cotato/bookitlist/security/CustomAuthenticationEntryPoint.java
  src/main/java/cotato/bookitlist/security/SecurityConfig.java
  src/main/java/cotato/bookitlist/security/jwt/AuthDetails.java
  src/main/java/cotato/bookitlist/security/jwt/JwtAuthenticationFilter.java
  src/main/java/cotato/bookitlist/security/jwt/JwtTokenProvider.java
  src/main/java/cotato/bookitlist/security/jwt/dto/AccessTokenInfo.java
  src/main/java/cotato/bookitlist/security/jwt/properties/JwtProperties.java
  src/main/java/cotato/bookitlist/security/oauth/AuthProvider.java
  src/main/java/cotato/bookitlist/security/oauth/KakaoOAuth2User.java
  src/main/java/cotato/bookitlist/security/oauth/NaverOAuth2User.java
  src/main/java/cotato/bookitlist/security/oauth/OAuth2UserInfo.java
  src/main/java/cotato/bookitlist/security/oauth/OAuth2UserInfoFactory.java
  src/main/java/cotato/bookitlist/security/oauth/UserPrincipal.java
  src/main/java/cotato/bookitlist/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/cotato/bookitlist/security/oauth/service/CustomOAuth2UserService.java
  src/test/java/cotato/bookitlist/factory/WithCustomMockUserFactory.java
  src/test/java/cotato/bookitlist/fixture/MemberFixture.java
Labels: 🧹 Chore
