Repository BookitList/BookitList_backend, pull requests merged in 2024-01, with the labels that each got.

#14 [Feat] Redis 이용한 책 저장 캐시 구현
  .github/workflows/deploy.yaml
  build.gradle
  src/main/java/cotato/bookitlist/book/domain/entity/Book.java
  src/main/java/cotato/bookitlist/book/domain/redis/BookApiCache.java
  src/main/java/cotato/bookitlist/book/repository/BookApiCacheRepository.java
  src/main/java/cotato/bookitlist/book/repository/BookRepository.java
  src/main/java/cotato/bookitlist/book/service/AladinService.java
  src/main/java/cotato/bookitlist/book/service/BookApiCacheService.java
  src/main/java/cotato/bookitlist/book/service/BookApiService.java
  src/main/java/cotato/bookitlist/book/service/BookService.java
  src/main/java/cotato/bookitlist/config/RedisConfig.java
  src/main/java/cotato/bookitlist/config/RestClientConfig.java
  src/main/java/cotato/bookitlist/mark/domain/MarkBook.java
  src/main/java/cotato/bookitlist/mark/domain/ReadBook.java
  src/main/java/cotato/bookitlist/post/domain/Post.java
  src/main/java/cotato/bookitlist/review/domain/Review.java
  src/main/resources/application.yaml
Labels: ✨ Feat, ✅ Test, 🧹 Chore

#16 [Feat] Swagger 설정 추가하기
  build.gradle
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
Labels: ✨ Feat, 📝 Docs

#18 [Feat] 새로운 책 등록하기
  build.gradle
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/main/java/cotato/bookitlist/book/domain/entity/Book.java
  src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
  src/main/java/cotato/bookitlist/book/dto/request/BookRegisterRequest.java
  src/main/java/cotato/bookitlist/book/repository/BookRepository.java
  src/main/java/cotato/bookitlist/book/service/AladinComponent.java
  src/main/java/cotato/bookitlist/book/service/AladinService.java
  src/main/java/cotato/bookitlist/book/service/BookApiCacheService.java
  src/main/java/cotato/bookitlist/book/service/BookApiComponent.java
  src/main/java/cotato/bookitlist/book/service/BookService.java
  src/main/java/cotato/bookitlist/common/exception/ErrorResponse.java
  src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
  src/main/java/cotato/bookitlist/config/JpaConfig.java
  src/main/java/cotato/bookitlist/config/RestClientConfig.java
  src/main/java/cotato/bookitlist/mark/domain/FollowUser.java
  src/main/java/cotato/bookitlist/mark/domain/LikePost.java
  src/main/java/cotato/bookitlist/mark/domain/LikeReview.java
  src/main/java/cotato/bookitlist/mark/domain/MarkBook.java
  src/main/java/cotato/bookitlist/mark/domain/ReadBook.java
  src/main/java/cotato/bookitlist/member/domain/Member.java
  src/main/java/cotato/bookitlist/post/domain/Post.java
  src/main/java/cotato/bookitlist/review/domain/Review.java
  src/main/resources/application.yaml
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
  src/test/resources/data.sql
Labels: ✨ Feat, ✅ Test

#21 [Feat] DB에서 책 조회 api 구현
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
  src/main/java/cotato/bookitlist/book/dto/BookDto.java
  src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
  src/main/java/cotato/bookitlist/book/dto/response/BookResponse.java
  src/main/java/cotato/bookitlist/book/repository/BookRepository.java
  src/main/java/cotato/bookitlist/book/service/BookApiComponent.java
  src/main/java/cotato/bookitlist/book/service/BookService.java
  src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
Labels: ✨ Feat, ♻️ Refactor, ✅ Test

#23 [Feat] sql로그를 예쁘게 보기위해 p6spy 도입
  build.gradle
  src/main/java/cotato/bookitlist/config/P6SpyConfig.java
  src/main/java/cotato/bookitlist/config/P6SpyEventListener.java
  src/main/java/cotato/bookitlist/config/P6SpyFormatter.java
  src/main/resources/application.yaml
Labels: ✨ Feat

#24 [Feat] OAuth 2.0를 활용한 로그인 구현
  build.gradle
  src/main/java/cotato/bookitlist/BookitlistApplication.java
  src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
  src/main/java/cotato/bookitlist/config/security/jwt/AuthDetails.java
  src/main/java/cotato/bookitlist/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/cotato/bookitlist/config/security/jwt/JwtTokenProvider.java
  src/main/java/cotato/bookitlist/config/security/jwt/dto/AccessTokenInfo.java
  src/main/java/cotato/bookitlist/config/security/jwt/properties/JwtProperties.java
  src/main/java/cotato/bookitlist/config/security/oauth/AuthProvider.java
  src/main/java/cotato/bookitlist/config/security/oauth/KakaoOAuth2User.java
  src/main/java/cotato/bookitlist/config/security/oauth/NaverOAuth2User.java
  src/main/java/cotato/bookitlist/config/security/oauth/OAuth2UserInfo.java
  src/main/java/cotato/bookitlist/config/security/oauth/OAuth2UserInfoFactory.java
  src/main/java/cotato/bookitlist/config/security/oauth/UserPrincipal.java
  src/main/java/cotato/bookitlist/config/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/cotato/bookitlist/config/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/cotato/bookitlist/member/domain/Member.java
  src/main/java/cotato/bookitlist/member/repository/MemberRepository.java
  src/main/resources/application-oauth.yaml
  src/main/resources/application.yaml
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
Labels: ✨ Feat

#27 [Feat] 설정값 외부 주입을 위한 deploy.yaml 파일 수정
  .github/workflows/deploy.yaml
Labels: ✨ Feat, 🧹 Chore

#33 [Feat] 로컬과 배포 환경에 따른 Swagger 설정, Swagger에서의 Authorization 설정
  src/main/java/cotato/bookitlist/config/SwaggerConfig.java
Labels: ✨ Feat

#35 [Feat] 책 검색 기능 수정
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/main/java/cotato/bookitlist/book/domain/entity/Book.java
  src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
  src/main/java/cotato/bookitlist/book/dto/request/BookRegisterRequest.java
  src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
  src/main/java/cotato/bookitlist/book/dto/response/BookResponse.java
  src/main/java/cotato/bookitlist/book/repository/BookRepository.java
  src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
  src/main/java/cotato/bookitlist/member/domain/Member.java
  src/main/java/cotato/bookitlist/post/domain/Post.java
  src/main/java/cotato/bookitlist/review/domain/Review.java
Labels: ✨ Feat, ♻️ Refactor

#37 [Feat] 배포중 테스트 실패 해결
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
Labels: 🐛 Fix, ✨ Feat, ✅ Test

#41 [Feat] 외부 api 요청에서 검색과 상세 조회 api 분리하기
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/main/java/cotato/bookitlist/book/controller/IsValidIsbn.java
  src/main/java/cotato/bookitlist/book/controller/IsbnValidator.java
  src/main/java/cotato/bookitlist/book/dto/BookApiDto.java
  src/main/java/cotato/bookitlist/book/dto/BookDto.java
  src/main/java/cotato/bookitlist/book/dto/request/BookRegisterRequest.java
  src/main/java/cotato/bookitlist/book/dto/response/BookApiListResponse.java
  src/main/java/cotato/bookitlist/book/dto/response/BookApiResponse.java
  src/main/java/cotato/bookitlist/book/dto/response/BookListResponse.java
  src/main/java/cotato/bookitlist/book/service/BookApiComponent.java
  src/main/java/cotato/bookitlist/book/service/BookService.java
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
Labels: ✨ Feat, ♻️ Refactor, ✅ Test

#43 [Feat] DB에 저장되어 있는 책 상세 조회 api 구현
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/main/java/cotato/bookitlist/book/dto/BookDto.java
  src/main/java/cotato/bookitlist/book/dto/response/BookResponse.java
  src/main/java/cotato/bookitlist/book/service/BookService.java
  src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
  src/test/java/cotato/bookitlist/book/controller/BookControllerTest.java
Labels: ✨ Feat, ✅ Test

#39 [Feat] Refresh Token & Black List (Redis) 구현
  src/main/java/cotato/bookitlist/auth/controller/AuthController.java
  src/main/java/cotato/bookitlist/auth/domain/BlackList.java
  src/main/java/cotato/bookitlist/auth/domain/RefreshTokenEntity.java
  src/main/java/cotato/bookitlist/auth/dto/request/LogoutRequest.java
  src/main/java/cotato/bookitlist/auth/dto/request/ReissueRequest.java
  src/main/java/cotato/bookitlist/auth/dto/response/ReissueResponse.java
  src/main/java/cotato/bookitlist/auth/repository/BlackListRepository.java
  src/main/java/cotato/bookitlist/auth/repository/RefreshTokenRepository.java
  src/main/java/cotato/bookitlist/auth/service/AuthService.java
  src/main/java/cotato/bookitlist/config/security/CustomAccessDeniedHandler.java
  src/main/java/cotato/bookitlist/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/cotato/bookitlist/config/security/SecurityConfig.java
  src/main/java/cotato/bookitlist/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/cotato/bookitlist/config/security/jwt/JwtTokenProvider.java
  src/main/java/cotato/bookitlist/config/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/cotato/bookitlist/global/controller/GlobalController.java
  src/main/resources/application.yaml
Labels: ✨ Feat, ♻️ Refactor

#47 [Feat] 게시글 생성 api 구현
  src/main/java/cotato/bookitlist/book/controller/BookController.java
  src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
  src/main/java/cotato/bookitlist/config/security/jwt/AuthDetails.java
  src/main/java/cotato/bookitlist/post/controller/PostController.java
  src/main/java/cotato/bookitlist/post/domain/Post.java
  src/main/java/cotato/bookitlist/post/dto/PostRegisterRequest.java
  src/main/java/cotato/bookitlist/post/repository/PostRepository.java
  src/main/java/cotato/bookitlist/post/service/PostService.java
  src/test/java/cotato/bookitlist/annotation/WithCustomMockUser.java
  src/test/java/cotato/bookitlist/factory/WithCustomMockUserFactory.java
  src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
  src/test/resources/data.sql
Labels: ✨ Feat, ✅ Test

#49 [Feat] 한줄요약 생성 API 개발
  src/main/java/cotato/bookitlist/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/cotato/bookitlist/review/controller/ReviewController.java
  src/main/java/cotato/bookitlist/review/domain/Review.java
  src/main/java/cotato/bookitlist/review/dto/request/ReviewRegisterRequest.java
  src/main/java/cotato/bookitlist/review/repository/ReviewRepository.java
  src/main/java/cotato/bookitlist/review/service/ReviewService.java
  src/main/resources/application-oauth.yaml
  src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
Labels: ✨ Feat, ✅ Test

#51 [Feat] 게시글 수정 api 구현
  src/main/java/cotato/bookitlist/common/exception/GlobalControllerAdvice.java
  src/main/java/cotato/bookitlist/post/controller/PostController.java
  src/main/java/cotato/bookitlist/post/domain/Post.java
  src/main/java/cotato/bookitlist/post/dto/PostUpdateRequest.java
  src/main/java/cotato/bookitlist/post/service/PostService.java
  src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
  src/test/resources/data.sql
Labels: 🐛 Fix, ✨ Feat, ✅ Test

#52 [Feat] 한줄요약 수정 API 구현
  src/main/java/cotato/bookitlist/review/controller/ReviewController.java
  src/main/java/cotato/bookitlist/review/domain/Review.java
  src/main/java/cotato/bookitlist/review/dto/request/ReviewUpdateRequest.java
  src/main/java/cotato/bookitlist/review/service/ReviewService.java
  src/test/java/cotato/bookitlist/review/controller/ReviewControllerTest.java
  src/test/resources/data.sql
Labels: 🐛 Fix, ✨ Feat, ✅ Test

#56 [Fix] 빌드 오류 수정
  src/main/java/cotato/bookitlist/review/controller/ReviewController.java
  src/main/java/cotato/bookitlist/review/service/ReviewService.java
Labels: 🐛 Fix

#57 [Feat] 게시글 조회 api 구현
  src/main/java/cotato/bookitlist/post/controller/PostController.java
  src/main/java/cotato/bookitlist/post/dto/PostDto.java
  src/main/java/cotato/bookitlist/post/dto/requeset/PostRegisterRequest.java
  src/main/java/cotato/bookitlist/post/dto/requeset/PostUpdateRequest.java
  src/main/java/cotato/bookitlist/post/dto/response/PostResponse.java
  src/main/java/cotato/bookitlist/post/service/PostService.java
  src/test/java/cotato/bookitlist/post/controller/PostControllerTest.java
Labels: ✨ Feat, ♻️ Refactor
